[platformio]
default_envs =
  mega2560
  esp32_bridge
  glove_sender
  glove_arduino_uno

[env:mega2560]
platform = atmelavr
board = megaatmega2560
framework = arduino
monitor_speed = 115200
build_src_filter =
  +<mega2560_controller.cpp>
  -<esp32_bridge.cpp>
  -<mega2560_arm_test.cpp>
  -<mega2560_car_arm_controller.cpp>
  -<voltage_monitor.cpp>

[env:esp32_bridge]
platform = espressif32@7.0.0
board = esp32dev
framework = arduino
monitor_speed = 115200
build_src_filter =
  +<esp32_bridge.cpp>
  -<mega2560_controller.cpp>
  -<mega2560_arm_test.cpp>
  -<mega2560_car_arm_controller.cpp>
  -<voltage_monitor.cpp>

[env:glove_sender]
platform = espressif32@7.0.0
board = esp32dev
framework = arduino
monitor_speed = 115200
build_src_filter =
  +<glove_sender.cpp>
  -<esp32_bridge.cpp>
  -<mega2560_controller.cpp>
  -<mega2560_arm_test.cpp>
  -<mega2560_car_arm_controller.cpp>
  -<voltage_monitor.cpp>

[env:glove_arduino_uno]
platform = atmelavr
board = uno
framework = arduino
monitor_speed = 115200
build_src_filter =
  +<glove_arduino_reader.cpp>
  -<glove_sender.cpp>
  -<esp32_bridge.cpp>
  -<mega2560_controller.cpp>
  -<mega2560_arm_test.cpp>
  -<mega2560_car_arm_controller.cpp>
  -<voltage_monitor.cpp>

[env:glove_arduino_mega]
platform = atmelavr
board = megaatmega2560
framework = arduino
monitor_speed = 115200
build_src_filter =
  +<glove_arduino_reader.cpp>
  -<glove_sender.cpp>
  -<esp32_bridge.cpp>
  -<mega2560_controller.cpp>
  -<mega2560_arm_test.cpp>
  -<mega2560_car_arm_controller.cpp>
  -<voltage_monitor.cpp>

[env:mega_command_relay]
platform = atmelavr
board = megaatmega2560
framework = arduino
monitor_speed = 115200
build_src_filter =
  +<mega_command_relay.cpp>
  -<glove_arduino_reader.cpp>
  -<glove_sender.cpp>
  -<esp32_bridge.cpp>
  -<esp32_car_command_sender.cpp>
  -<mega2560_controller.cpp>
  -<mega2560_arm_test.cpp>
  -<mega2560_car_arm_controller.cpp>
  -<voltage_monitor.cpp>

[env:mega_pot_arm_controller]
platform = atmelavr
board = megaatmega2560
framework = arduino
monitor_speed = 115200
build_src_filter =
  +<mega_pot_arm_controller.cpp>
  -<mega_command_relay.cpp>
  -<glove_arduino_reader.cpp>
  -<glove_sender.cpp>
  -<esp32_bridge.cpp>
  -<esp32_car_command_sender.cpp>
  -<mega2560_controller.cpp>
  -<mega2560_arm_test.cpp>
  -<mega2560_car_arm_controller.cpp>
  -<voltage_monitor.cpp>
  -<pot_threshold_tester.cpp>

[env:pot_threshold_tester]
platform = atmelavr
board = megaatmega2560
framework = arduino
monitor_speed = 115200
build_src_filter =
  +<pot_threshold_tester.cpp>
  -<mega_pot_arm_controller.cpp>
  -<mega_command_relay.cpp>
  -<glove_arduino_reader.cpp>
  -<glove_sender.cpp>
  -<esp32_bridge.cpp>
  -<esp32_car_command_sender.cpp>
  -<mega2560_controller.cpp>
  -<mega2560_arm_test.cpp>
  -<mega2560_car_arm_controller.cpp>
  -<voltage_monitor.cpp>

[env:esp32_car_command_sender]
platform = espressif32@7.0.0
board = esp32dev
framework = arduino
monitor_speed = 115200
build_src_filter =
  +<esp32_car_command_sender.cpp>
  -<mega_command_relay.cpp>
  -<glove_arduino_reader.cpp>
  -<glove_sender.cpp>
  -<esp32_bridge.cpp>
  -<mega2560_controller.cpp>
  -<mega2560_arm_test.cpp>
  -<mega2560_car_arm_controller.cpp>
  -<voltage_monitor.cpp>

[env:mega2560_arm_test]
platform = atmelavr
board = megaatmega2560
framework = arduino
monitor_speed = 115200
lib_deps =
  arduino-libraries/Servo
build_src_filter =
  +<mega2560_arm_test.cpp>
  -<mega2560_controller.cpp>
  -<esp32_bridge.cpp>
  -<mega2560_car_arm_controller.cpp>
  -<voltage_monitor.cpp>

[env:mega2560_car_arm]
platform = atmelavr
board = megaatmega2560
framework = arduino
monitor_speed = 115200
lib_deps =
  arduino-libraries/Servo
build_src_filter =
  +<mega2560_car_arm_controller.cpp>
  -<mega2560_controller.cpp>
  -<mega2560_arm_test.cpp>
  -<esp32_bridge.cpp>
  -<voltage_monitor.cpp>

[env:arduino_voltage_monitor]
platform = atmelavr
board = megaatmega2560
framework = arduino
monitor_speed = 115200
upload_port = COM10
monitor_port = COM10
build_src_filter =
  +<voltage_monitor.cpp>
  -<mega2560_controller.cpp>
  -<esp32_bridge.cpp>
  -<mega2560_arm_test.cpp>
  -<mega2560_car_arm_controller.cpp>

[env:uno_voltage_monitor]
platform = atmelavr
board = uno
framework = arduino
monitor_speed = 115200
build_src_filter =
  +<voltage_monitor.cpp>
  -<mega2560_controller.cpp>
  -<esp32_bridge.cpp>
  -<mega2560_arm_test.cpp>
  -<mega2560_car_arm_controller.cpp>
