[platformio]
default_envs =
  mega2560
  esp32_bridge

[env:mega2560]
platform = atmelavr
board = megaatmega2560
framework = arduino
monitor_speed = 115200
build_src_filter =
  +<mega2560_controller.cpp>
  -<esp32_bridge.cpp>
  -<mega2560_arm_test.cpp>
  -<mega2560_car_arm_controller.cpp>
  -<voltage_monitor.cpp>

[env:esp32_bridge]
platform = espressif32@7.0.0
board = esp32dev
framework = arduino
monitor_speed = 115200
build_src_filter =
  +<esp32_bridge.cpp>
  -<mega2560_controller.cpp>
  -<mega2560_arm_test.cpp>
  -<mega2560_car_arm_controller.cpp>
  -<voltage_monitor.cpp>

[env:mega2560_arm_test]
platform = atmelavr
board = megaatmega2560
framework = arduino
monitor_speed = 115200
lib_deps =
  arduino-libraries/Servo
build_src_filter =
  +<mega2560_arm_test.cpp>
  -<mega2560_controller.cpp>
  -<esp32_bridge.cpp>
  -<mega2560_car_arm_controller.cpp>
  -<voltage_monitor.cpp>

[env:mega2560_car_arm]
platform = atmelavr
board = megaatmega2560
framework = arduino
monitor_speed = 115200
lib_deps =
  arduino-libraries/Servo
build_src_filter =
  +<mega2560_car_arm_controller.cpp>
  -<mega2560_controller.cpp>
  -<mega2560_arm_test.cpp>
  -<esp32_bridge.cpp>
  -<voltage_monitor.cpp>

[env:arduino_voltage_monitor]
platform = atmelavr
board = megaatmega2560
framework = arduino
monitor_speed = 115200
upload_port = COM10
monitor_port = COM10
build_src_filter =
  +<voltage_monitor.cpp>
  -<mega2560_controller.cpp>
  -<esp32_bridge.cpp>
  -<mega2560_arm_test.cpp>
  -<mega2560_car_arm_controller.cpp>

[env:uno_voltage_monitor]
platform = atmelavr
board = uno
framework = arduino
monitor_speed = 115200
build_src_filter =
  +<voltage_monitor.cpp>
  -<mega2560_controller.cpp>
  -<esp32_bridge.cpp>
  -<mega2560_arm_test.cpp>
  -<mega2560_car_arm_controller.cpp>
