[platformio]
default_envs =
  mega2560
  esp32_bridge

[env:mega2560]
platform = atmelavr
board = megaatmega2560
framework = arduino
monitor_speed = 115200
build_flags =
  -IC:/Users/Max/.platformio/packages/framework-arduinoespressif32/cores/esp32
  -IC:/Users/Max/.platformio/packages/framework-arduinoespressif32/variants/esp32
  -IC:/Users/Max/.platformio/packages/framework-arduinoespressif32/libraries/WiFi/src
  -IC:/Users/Max/.platformio/packages/framework-arduinoespressif32/libraries/Network/src
  -IC:/Users/Max/.platformio/packages/framework-arduinoespressif32/libraries/WebServer/src
  -IC:/Users/Max/.platformio/packages/framework-arduinoespressif32/libraries/FS/src
build_src_filter =
  +<mega2560_controller.cpp>
  -<esp32_bridge.cpp>

[env:esp32_bridge]
platform = espressif32@7.0.0
board = esp32dev
framework = arduino
monitor_speed = 115200
build_src_filter =
  +<esp32_bridge.cpp>
  -<mega2560_controller.cpp>
